const STUDENT_LOGIN_LOADING = 'STUDENT_LOGIN_LOADING';
const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
const STUDENT_LOGIN_FAILURE = 'STUDENT_LOGIN_FAILURE';
const STUDENT_SELECT_SUCCESS = 'STUDENT_SELECT_SUCCESS';

export {
  STUDENT_LOGIN_LOADING,
  STUDENT_LOGIN_SUCCESS,
  STUDENT_LOGIN_FAILURE,
  STUDENT_SELECT_SUCCESS,
};
