const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
const AUTH_SET_STUDENTS = 'AUTH_SET_STUDENTS';
const AUTH_SET_STUDENT = 'AUTH_SET_STUDENT';

export {
  AUTH_LOGIN_LOADING,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAILURE,
  AUTH_SET_STUDENTS,
  AUTH_SET_STUDENT,
};
